table city_difficulty
	lineageTag: ce64f952-57ad-4d0f-803b-bb948519b1cd
	sourceLineageTag: [dbo].[city_difficulty]

	measure Measure
		lineageTag: 88da8ebf-fe34-47df-aa48-6ba5e4255315

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure 'Measure 2'
		lineageTag: faf59c20-e60b-479e-a289-999871183814

		annotation 43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c = True

	measure 'Hint Success Rate' =
			
			AVERAGE(hint_performance[success_after_hint_rate])
		formatString: #,0%;-#,0%;#,0%
		lineageTag: cc4c2925-241b-4d3a-9835-e44a8f2f3f5e

		changedProperty = Name

		changedProperty = FormatString

	measure 'Most Difficult City Real' =
			
			VAR TopCity =
			    TOPN(
			        1,
			        city_difficulty,
			        city_difficulty[difficulty_real],
			        DESC
			    )
			RETURN
			    MAXX(
			        TopCity,
			        RELATED(dim_city_gold[city_name])
			            & " ("
			            & FORMAT(city_difficulty[difficulty_real], "0.00")
			            & ")"
			    )
		lineageTag: 596e984e-7683-43e1-ba6a-3729eda8e396

		changedProperty = Name

	column city_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 367b6232-b32c-4b53-ba09-c7db4f7a490c
		sourceLineageTag: city_id
		summarizeBy: none
		sourceColumn: city_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column nb_sessions
		dataType: int64
		formatString: 0
		lineageTag: 95735da6-553b-4d19-b0e4-047f45237eeb
		sourceLineageTag: nb_sessions
		summarizeBy: sum
		sourceColumn: nb_sessions

		annotation SummarizationSetBy = Automatic

	column difficulty_initial
		dataType: double
		lineageTag: f570cbb8-f7c1-42c5-a9c3-c5a6472b5e3f
		sourceLineageTag: difficulty_initial
		summarizeBy: sum
		sourceColumn: difficulty_initial

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column difficulty_real
		dataType: double
		lineageTag: 3294eefe-d0d7-4041-806c-60e02d59d1d9
		sourceLineageTag: difficulty_real
		summarizeBy: sum
		sourceColumn: difficulty_real

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column difficulty_score
		dataType: double
		lineageTag: 8822ef1f-1ac2-4233-8528-7b4cebf9b38b
		sourceLineageTag: difficulty_score
		summarizeBy: sum
		sourceColumn: difficulty_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column event_source
		dataType: string
		lineageTag: 33046097-5629-47be-b903-8bf23e4bff6e
		sourceLineageTag: event_source
		summarizeBy: none
		sourceColumn: event_source

		annotation SummarizationSetBy = Automatic

	column is_simulated
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7948b175-9a9d-4e36-b905-6b349b7b1061
		sourceLineageTag: is_simulated
		summarizeBy: none
		sourceColumn: is_simulated

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column difficulty_level
		dataType: int64
		formatString: 0
		lineageTag: 9fa0e772-d386-40e4-93d3-644a38bc56f9
		sourceLineageTag: difficulty_level
		summarizeBy: sum
		sourceColumn: difficulty_level

		annotation SummarizationSetBy = Automatic

	partition city_difficulty = entity
		mode: directLake
		source
			entityName: city_difficulty
			schemaName: dbo
			expressionSource: 'DirectLake - wh_gold'

