table hint_performance
	lineageTag: e6cb7ffe-16f9-4da0-a84d-b2eebdfc43f9
	sourceLineageTag: [dbo].[hint_performance]

	measure 'Best Hint' =
			
			VAR BestHintRow =
			    TOPN(
			        1,
			        ALLSELECTED(hint_performance[hint_label]),
			        [Hint Success Rate],
			        DESC
			    )
			RETURN
			    MAXX(
			        BestHintRow,
			        hint_performance[hint_label]
			            & " ("
			            & FORMAT([Hint Success Rate], "0%")
			            & ")"
			    )
		lineageTag: 745a462e-8bb5-45fe-961c-22d8c17772f4

		changedProperty = Name

	measure 'Worst Hint' =
			
			VAR WorstHintRow =
			    TOPN(
			        1,
			        ALLSELECTED(hint_performance[hint_label]),
			        [Hint Success Rate],
			        ASC
			    )
			RETURN
			    MAXX(
			        WorstHintRow,
			        hint_performance[hint_label]
			            & " ("
			            & FORMAT([Hint Success Rate], "0%")
			            & ")"
			    )
		lineageTag: d89e3982-b0f7-4407-95ec-6ca08a74c774

		changedProperty = Name

	measure 'Avg Hint Success Rate' =
			
			DIVIDE(
			    SUMX(
			        hint_performance,
			        hint_performance[success_after_hint_rate]
			            * hint_performance[total_requested]
			    ),
			    SUM(hint_performance[total_requested])
			)
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 1e55b154-e9de-41cc-91ca-cf68728d6c65

		changedProperty = Name

		changedProperty = FormatString

	column hint_id
		dataType: int64
		formatString: 0
		lineageTag: e477cb16-7d49-4e1f-b721-c550de0c69ae
		sourceLineageTag: hint_id
		summarizeBy: none
		sourceColumn: hint_id

		annotation SummarizationSetBy = Automatic

	column hint_label
		dataType: string
		lineageTag: 02d5473a-c215-484e-b610-7c2ab8eb223f
		sourceLineageTag: hint_label
		summarizeBy: none
		sourceColumn: hint_label

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column hint_stage
		dataType: string
		lineageTag: 10735941-80c6-4007-94ac-76a81a197275
		sourceLineageTag: hint_stage
		summarizeBy: none
		sourceColumn: hint_stage

		changedProperty = FormatString

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column total_requested
		dataType: int64
		formatString: 0
		lineageTag: f69bbf5c-ac1a-483a-86b9-5e8a91b9ef9b
		sourceLineageTag: total_requested
		summarizeBy: sum
		sourceColumn: total_requested

		annotation SummarizationSetBy = Automatic

	column total_shown
		dataType: int64
		formatString: 0
		lineageTag: 183d0bac-0a95-44ff-8895-c134e88cc34b
		sourceLineageTag: total_shown
		summarizeBy: sum
		sourceColumn: total_shown

		annotation SummarizationSetBy = Automatic

	column avg_guesses_after_hint
		dataType: decimal
		formatString: 0
		lineageTag: 998055e7-5372-4135-b135-88988df77fda
		sourceLineageTag: avg_guesses_after_hint
		summarizeBy: sum
		sourceColumn: avg_guesses_after_hint

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	column success_after_hint_rate
		dataType: decimal
		formatString: 0%;-0%;0%
		lineageTag: f9054f45-a4f4-4a51-9370-6a24b7d8ece5
		sourceLineageTag: success_after_hint_rate
		summarizeBy: sum
		sourceColumn: success_after_hint_rate

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

	column event_source
		dataType: string
		lineageTag: c16b7005-c0ab-40bb-a4d4-922c17faf375
		sourceLineageTag: event_source
		summarizeBy: none
		sourceColumn: event_source

		annotation SummarizationSetBy = Automatic

	column is_simulated
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 68913c2d-fb58-4c59-9642-58a81cbf0543
		sourceLineageTag: is_simulated
		summarizeBy: none
		sourceColumn: is_simulated

		annotation SummarizationSetBy = Automatic

	partition hint_performance = entity
		mode: directLake
		source
			entityName: hint_performance
			schemaName: dbo
			expressionSource: 'DirectLake - wh_gold'

