CREATE TABLE [dbo].[city_game_context] (

	[city_id] bigint NULL, 
	[city_name] varchar(255) NULL, 
	[hemisphere] varchar(50) NULL, 
	[global_quadrant] varchar(50) NULL, 
	[longitudinal_zone] varchar(100) NULL, 
	[is_capital] bit NULL, 
	[coastal_distance_category] varchar(100) NULL, 
	[altitude_category] varchar(100) NULL, 
	[city_category] varchar(100) NULL, 
	[city_name_length_category] varchar(100) NULL, 
	[city_word_count_category] varchar(100) NULL, 
	[city_first_letter] varchar(10) NULL, 
	[city_last_letter] varchar(10) NULL, 
	[continent] varchar(100) NULL, 
	[country_name] varchar(255) NULL, 
	[country_density_category] varchar(100) NULL, 
	[country_category] varchar(100) NULL, 
	[languages_count] int NULL, 
	[currency_name] varchar(100) NULL, 
	[neighbours_count] int NULL, 
	[temperature] decimal(10,2) NULL, 
	[weather_type] varchar(100) NULL, 
	[timezone_offset_sec] int NULL, 
	[utc_offset_hours] decimal(4,1) NULL, 
	[is_weather_available] bit NULL, 
	[is_local_time_available] bit NULL, 
	[difficulty_initial] decimal(10,4) NULL, 
	[difficulty_simulated] decimal(10,4) NULL, 
	[difficulty_real] decimal(10,4) NULL, 
	[difficulty_score_default] decimal(10,4) NULL, 
	[nb_sessions_simulated] int NULL, 
	[nb_sessions_real] int NULL
);